---
- name: Provision AMI image with GCI VPN Components
  remote_user: ec2-user
  hosts: default
  vars:
    target_major_version: "{{ ansible_facts['distribution_major_version'] }}"
    target_family: "{{ ansible_facts['os_family']|lower }}"
    target: "{{ target_family }}{{ target_major_version }}"

  tasks:
    - debug:
        msg: "home_location: {{ home_location }}"

    - debug:
        msg: "git_branch: {{ git_branch }}"

    - import_role:
        name: hub-base
      vars:
        nrts_src_version: ""  # currently unused, but should in future, pull from github "release" version
        system_hostname: nrtshub
        home_root: "{{ home_location }}"
        nrts_home_dir : "{{ home_location }}/nrts"
        git_src_branch: "{{ git_branch }}"

    - name: install system pkgs
      ansible.builtin.dnf:
        name: "{{ pkgs }}"
        state: latest
        update_cache: yes
        allowerasing: true
      become: true
      vars:
        pkgs: 
          - docker
          - gnupg2-full
          - gpg-agent


