---
- name: Provision AMI image with GCI VPN Components
  remote_user: ec2-user
  hosts: default
  vars:
    target_major_version: "{{ ansible_facts['distribution_major_version'] }}"
    target_family: "{{ ansible_facts['os_family']|lower }}"
    target: "{{ target_family }}{{ target_major_version }}"

  tasks:
    - debug:
        msg: "home_location: {{ home_location }}"

    - debug:
        msg: "git_branch: {{ git_branch }}"

    - name: install system pkgs
      ansible.builtin.dnf:
        name: "{{ pkgs }}"
        state: latest
        update_cache: yes
        allowerasing: true
      become: true
      vars:
        pkgs: 
          - docker
          - gnupg2-full

    - name: add users to docker group for C&C
      ansible.builtin.user:
        name: "{{ item }}"
        append: true
        groups: 'docker'
      become: true
      loop:
        - "nrts"
        - "ec2-user"
    
    - name: start docker daemon
      ansible.builtin.systemd_service:
        become: yes
        become_user: nrts
        name: docker
        enabled: true
        state: started
