- name: add /gsn mount script to crontab
  ansible.builtin.cron:
    special_time: "reboot"
    job: "/usr/local/scripts/mount-s3fgw-gsn.sh"
    name: "mount /gsn"
    # dest: "{{ deploy_root }}/{{ item.target }}"
  become: yes
  become_user: gsndcc

- name: append GSN hosts to /etc/hosts
  lineinfile: path=/etc/hosts line={{lookup('file', '../templates/dcc-hosts')}} create=yes state=present

- name: deploy path_add.csh
  ansible.builtin.copy:
    remote_src: false
    src: ../templates/pathadd.csh
    dest: /usr/local/pathadd.csh
    mode: 775
    backup: yes
  become: true

- name: use gsndcc .cshrc for user nrts also (just on GSNDCC)
  ansible.builtin.copy:
    remote_src: false
    src: ../templates/gsndcc-cshrc
    dest: "~/.cshrc"
    mode: 664
    backup: yes
  become: true
  become_user: nrts

##########################################
### NEED TO MOVE TO A 'config' SCRIPT for management, like nrts-config
- name: deploy IDA/GSN user gsndcc startup files
  ansible.builtin.copy:
    remote_src: false
    src: "../templates/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    backup: yes
  loop:
    - { src: gsndcc-aliases, dest: .aliases }
    - { src: gsndcc-cshrc, dest: .cshrc }
  become: true
  become_user: gsndcc


- name: deploy IDA/GSN system startup files
  ansible.builtin.copy:
    remote_src: false
    src: "../templates/{{ item.src }}"
    dest: "/usr/local/{{ item.dest }}"
    backup: yes
  loop:
    - { src: dcc-bashrc, dest: bashrc }
    - { src: dcc-cshrc, dest: cshrc }
    - { src: dcc-devenv.csh, dest: devenv.csh }
    - { src: dcc-devenv.sh, dest: devenv.sh }
  become: true
##########################################


