- name: get DCC source repositories
  ansible.builtin.git:
    repo: "https://github.com/projectida/{{ item.repo }}.git"
    dest: "{{ deploy_root }}/{{ item.target }}"
    accept_hostkey: yes
  become: yes
  # become_user: nrts
  loop:
    - { repo: dcc-scripts, target: scripts }
    - { repo: dcc-modules-py, target: modules-py }
  tags:
    - dccbuild

